name: Construire APK TikIA

on:
  workflow_dispatch:
  push:
    branches:
      - Principaux

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Donner les permissions à Gradle
        run: chmod +x gradlew

      - name: Construire l'APK
        run: ./gradlew :Application:assembleDebug

      - name: Télécharger l'APK
        uses: actions/upload-artifact@v4
        with:
          name: TikIA-APK
          path: Application/build/outputs/apk/debug/*.apk
